#!/usr/bin/env bash
set -euo pipefail

# Regenerates all figures used in Chapter 7 (generated by Meep).
# Prerequisite: conda-forge pymeep environment (default: meep-book)
#
# Example:
#   ./scripts/gen_ch07_figs.sh
#
# Override via variables:
#   ENV_NAME=meep-book MAMBA=$HOME/miniforge3/bin/mamba ./scripts/gen_ch07_figs.sh

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_dir"

ENV_NAME="${ENV_NAME:-meep-book}"
MAMBA="${MAMBA:-$HOME/miniforge3/bin/mamba}"

if [[ ! -x "$MAMBA" ]]; then
  echo "error: mamba not found: $MAMBA" >&2
  echo "hint: set MAMBA=... or install Miniforge." >&2
  exit 1
fi

run_py() {
  "$MAMBA" run -n "$ENV_NAME" python "$@"
}

run_py code/ch07/microstrip_step_sparams.py

echo "generated: figs/ch07/*.png"
