#!/usr/bin/env bash
set -euo pipefail

# Regenerates all figures used in Chapter 9 (generated by Meep).
# Prerequisite: conda-forge pymeep environment (default: meep-book)
#
# Example:
#   ./scripts/gen_ch09_figs.sh
#
# Override via variables:
#   ENV_NAME=meep-book MAMBA=$HOME/miniforge3/bin/mamba ./scripts/gen_ch09_figs.sh
#   CH09_FORCE_REGEN=1 ./scripts/gen_ch09_figs.sh

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_dir"

ENV_NAME="${ENV_NAME:-meep-book}"
MAMBA="${MAMBA:-$HOME/miniforge3/bin/mamba}"

if [[ ! -x "$MAMBA" ]]; then
  echo "error: mamba not found: $MAMBA" >&2
  echo "hint: set MAMBA=... or install Miniforge." >&2
  exit 1
fi

run_py() {
  "$MAMBA" run -n "$ENV_NAME" python "$@"
}

run_py code/ch09/microstrip_stub_notch.py
run_py code/ch09/microstrip_short_stub_rf_open.py

echo "generated: figs/ch09/*.png"
