#!/usr/bin/env bash
set -euo pipefail

# Regenerates all figures used in Chapter 8 (generated by Meep).
# Prerequisite: conda-forge pymeep environment (default: meep-book)
# For CAD/STEP figures: conda-forge cadquery environment (default: meep-cad)
#
# Example:
#   ./scripts/gen_ch08_figs.sh
#
# Override via variables:
#   ENV_NAME=meep-book MAMBA=$HOME/miniforge3/bin/mamba ./scripts/gen_ch08_figs.sh
#   CAD_ENV_NAME=meep-cad ./scripts/gen_ch08_figs.sh
#   CH08_FORCE_REGEN=1 ./scripts/gen_ch08_figs.sh

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_dir"

ENV_NAME="${ENV_NAME:-meep-book}"
MAMBA="${MAMBA:-$HOME/miniforge3/bin/mamba}"

if [[ ! -x "$MAMBA" ]]; then
  echo "error: mamba not found: $MAMBA" >&2
  echo "hint: set MAMBA=... or install Miniforge." >&2
  exit 1
fi

run_py() {
  "$MAMBA" run -n "$ENV_NAME" python "$@"
}

run_py code/ch08/01_dipole_baseline.py
run_py code/ch08/07_cross_dipole_cp.py

CAD_ENV_NAME="${CAD_ENV_NAME:-meep-cad}"
if "$MAMBA" env list | awk '{print $1}' | grep -qx "$CAD_ENV_NAME"; then
  "$MAMBA" run -n "$CAD_ENV_NAME" python code/ch08/cad_models.py
else
  echo "skip: CAD env not found: $CAD_ENV_NAME" >&2
  echo "hint: $MAMBA env create -f environment_cad.yml" >&2
fi

echo "generated: figs/ch08/*.png"
